In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame([[1,2,3,4],[5,6,7,8],[2,7,3,23],[3,6,8,23],[23,23,63,12]], columns=['A', 'B', 'C', 'D'])
df1

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   2   7   3  23
3   3   6   8  23
4  23  23  63  12

In [3]:
df1.shape

(5, 4)

In [4]:
df1.iloc[0,1]

2

In [5]:
df1.iloc[0:2,0:2] #slices a perticular matrix

   A  B
0  1  2
1  5  6

In [6]:
df1.iloc[0:2,1:3]

   B  C
0  2  3
1  6  7

In [7]:
df1.drop(['B', 'C'], axis=1) #drops column B and C

    A   D
0   1   4
1   5   8
2   2  23
3   3  23
4  23  12

In [8]:
df1.drop(columns=['B', 'C']) #does the same job

    A   D
0   1   4
1   5   8
2   2  23
3   3  23
4  23  12

In [9]:
df1.drop([1, 2]) #drops the rows

    A   B   C   D
0   1   2   3   4
3   3   6   8  23
4  23  23  63  12

In [10]:
df1.drop([0, 3])

    A   B   C   D
1   5   6   7   8
2   2   7   3  23
4  23  23  63  12