In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame() #creating an empty Data Frame

In [3]:
df

Empty DataFrame
Columns: []
Index: []

In [4]:
print(df)

Empty DataFrame
Columns: []
Index: []

In [5]:
df1 = pd.DataFrame([[1,2,3,4],[5,6,7,8],[2,7,3,23],[3,6,8,23],[23,23,63,12]])

In [6]:
df1 #this table is only shown in jupyter notebook

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   2   7   3  23
3   3   6   8  23
4  23  23  63  12

In [7]:
df1.head()

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   2   7   3  23
3   3   6   8  23
4  23  23  63  12

In [8]:
df1.head(3) #takes first three rows and columns

   0  1  2   3
0  1  2  3   4
1  5  6  7   8
2  2  7  3  23

In [9]:
df1.tail(3) #takes last three rows and columns

    0   1   2   3
2   2   7   3  23
3   3   6   8  23
4  23  23  63  12