In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data1.CSV')

In [3]:
df

,TRADE_NO,TRADE_TIME,SECTYPE,SECURITY,ISSUE_NAME,TRADE_TYPE,TRADE_DT,SETTL_DT,TRADE_QTY (Rs in Lacs),PRICE_RATE(Rs.),PRICE_YIELD,ISSUE_DATE,COUPON FREQUENCY,MAT_DATE
0,1,10:41:15,GS,CG2017,8.07%,NR,01-Jan-03,01-Jan-03,500.0,117.08,6.227,15-Jan-02,HALF-YEARLY,15-Jan-17
1,2,10:41:24,GS,CG2017,7.49%,NR,01-Jan-03,01-Jan-03,500.0,111.95,6.216,16-Apr-02,HALF-YEARLY,16-Apr-17
2,3,10:41:26,GS,CG2017,7.46%,NR,01-Jan-03,01-Jan-03,500.0,111.90,6.209,28-Aug-02,HALF-YEARLY,28-Aug-17
3,4,10:41:29,GS,CG2017,7.46%,NR,01-Jan-03,01-Jan-03,500.0,111.89,6.210,28-Aug-02,HALF-YEARLY,28-Aug-17
4,5,10:41:31,GS,CG2017,7.49%,NR,01-Jan-03,01-Jan-03,500.0,112.00,6.211,16-Apr-02,HALF-YEARLY,16-Apr-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20670,352,17:15:43,GS,CG2017,8.07%,NR,31-Jan-03,01-Feb-03,500.0,115.00,6.430,15-Jan-02,HALF-YEARLY,15-Jan-17
20671,353,17:15:45,GS,CG2017,7.46%,NR,31-Jan-03,01-Feb-03,500.0,109.15,6.480,28-Aug-02,HALF-YEARLY,28-Aug-17
20672,354,17:15:48,GS,CG2012,9.40%,NR,31-Jan-03,01-Feb-03,500.0,121.25,6.409,11-Sep-01,HALF-YEARLY,11-Sep-12
20673,355,17:28:06,GS,CG2013,9.81%,NR,31-Jan-03,01-Feb-03,500.0,126.35,6.304,30-May-01,HALF-YEARLY,30-May-13
20674,357,17:37:04,GS,CG2012,7.40%,NR,31-Jan-03,01-Feb-03,500.0,107.80,6.278,03-May-02,HALF-YEARLY,03-May-12

In [4]:
df.head()

,TRADE_NO,TRADE_TIME,SECTYPE,SECURITY,ISSUE_NAME,TRADE_TYPE,TRADE_DT,SETTL_DT,TRADE_QTY (Rs in Lacs),PRICE_RATE(Rs.),PRICE_YIELD,ISSUE_DATE,COUPON FREQUENCY,MAT_DATE
0,1,10:41:15,GS,CG2017,8.07%,NR,01-Jan-03,01-Jan-03,500.0,117.08,6.227,15-Jan-02,HALF-YEARLY,15-Jan-17
1,2,10:41:24,GS,CG2017,7.49%,NR,01-Jan-03,01-Jan-03,500.0,111.95,6.216,16-Apr-02,HALF-YEARLY,16-Apr-17
2,3,10:41:26,GS,CG2017,7.46%,NR,01-Jan-03,01-Jan-03,500.0,111.90,6.209,28-Aug-02,HALF-YEARLY,28-Aug-17
3,4,10:41:29,GS,CG2017,7.46%,NR,01-Jan-03,01-Jan-03,500.0,111.89,6.210,28-Aug-02,HALF-YEARLY,28-Aug-17
4,5,10:41:31,GS,CG2017,7.49%,NR,01-Jan-03,01-Jan-03,500.0,112.00,6.211,16-Apr-02,HALF-YEARLY,16-Apr-17

In [5]:
df['SECURITY'].dtype # 'O' for Object

dtype('O')

In [6]:
print(df['SECURITY'].dtype)

object

In [7]:
df['PRICE_YIELD'] # provides length as well as datatypes

0        6.227
1        6.216
2        6.209
3        6.210
4        6.211
         ...
20670    6.430
20671    6.480
20672    6.409
20673    6.304
20674    6.278
Name: PRICE_YIELD, Length: 20675, dtype: float64

In [8]:
print(df['SECURITY'].astype('category'))

0        CG2017
1        CG2017
2        CG2017
3        CG2017
4        CG2017
          ...
20670    CG2017
20671    CG2017
20672    CG2012
20673    CG2013
20674    CG2012
Name: SECURITY, Length: 20675, dtype: category
Categories (25, object): ['364D', '91D', 'CG2003', 'CG2004', ..., 'CG2021', 'CG2022', 'CG2026', 'CG2032']